analytics_nginx_configs:
  proxy:
    - proxy_set_header X-Real-IP  $remote_addr
    - proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for
  gzip:
    - gzip on
    - gzip_proxied any
    - gzip_types text/plain text/xml text/css application/x-javascript
    - gzip_vary on
    - gzip_disable "MSIE [1-6]\.(?!.*SV1)"
    - gzip_static on

analytics_nginx_iglu:
  - "listen {{snowplow_iglu_bind_port}}"
  - "listen [::]:{{snowplow_iglu_bind_port}}"
  - server_name localhost
  - "location /schemas/ {
      alias {{snowplow_stream_enrich_installation_folder}}/iglu/schemas/;
    }
  "

analytics_nginx_http:
  - listen 80
  - listen [::]:80
  - server_name {{analytics_domain_name}}
  - "location / {
      rewrite ^ https://$server_name$request_uri? permanent;
    }
  "
  - "location ~ /.well-known/acme-challenge/ {
      alias {{nginx_root_folder}}/.well-known/acme-challenge/;
    }"

analytics_nginx_https_common:
  - listen 443 ssl
  - listen [::]:443
  - server_name {{analytics_domain_name}}
  - ssl_certificate /etc/letsencrypt/live/{{analytics_domain_name}}/fullchain.pem
  - ssl_certificate_key  /etc/letsencrypt/live/{{analytics_domain_name}}/privkey.pem
  - ssl_session_timeout 5m
  - ssl_protocols TLSv1 TLSv1.1 TLSv1.2
  - ssl_ciphers ALL:!ADH:!EXPORT56:RC4+RSA:+HIGH:+MEDIUM:+LOW:+SSLv3:+EXP
  - ssl_prefer_server_ciphers on
  - "location / {
      return 301 {{analytics_not_found_redirect}};
    }"
  - "location ~ /.well-known/acme-challenge/ {
      alias {{nginx_root_folder}}/.well-known/acme-challenge/;
    }"
  - "location /i {
      proxy_pass http://{{snowplow_stream_collector_bind_host}}:{{snowplow_stream_collector_bind_port}};
    }"

analytics_nginx_https_standard_mode:
  - "location {{analytics_path}} {
      alias {{analytics_js_installation_folder}};
    }"

analytics_nginx_https_dev_mode:
  - "location {{analytics_path}} {
      proxy_pass http://10.10.10.1:3000/;
    }"
  - "location /__webpack_hmr {
      proxy_set_header Connection '';
      proxy_http_version 1.1;
      chunked_transfer_encoding off;
      proxy_buffering off;
      proxy_cache off;
      proxy_pass http://10.10.10.1:3000/__webpack_hmr;
    }"
  - "location ~ hot-update.js(on)?(.map)?$ {
      proxy_pass http://10.10.10.1:3000;
    }"
